#! /usr/bin/env python
# -*- coding: utf-8 -*-

import argparse
import logging
from time import sleep

from gavin.client import Client
from gavin.gavin import GUIDE_USB_DEVICE_INFO_T

logging.basicConfig(level=logging.DEBUG)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Gavin camera command-line option',
                                     formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument('--id', type=int, default=0, help='Device ID')
    parser.add_argument('--width', type=int, default=640, help='Video width')
    parser.add_argument('--height', type=int, default=512, help='Video height')
    parser.add_argument('--mode', type=int, default=0, help='Video mode')
    args = parser.parse_args()

    with Client() as cam:   # Либо cam.Initialize() в начале и cam.Exit() в конце
        devices = cam.GetDeviceList()

        device_info = GUIDE_USB_DEVICE_INFO_T()
        device_info.width = args.width
        device_info.height = args.height
        device_info.video_mode = args.mode
        if cam.OpenStreamByDevID(dev_id=devices.devs[args.id].devID, dev_info=device_info):
            try:
                while True:
                    sleep(0.1)
            except KeyboardInterrupt:
                pass

            cam.CloseStream()
